### PR TITLE
Run docs nightly

### PR DESCRIPTION
**Pull request by AyodeAwe**
This PR configures `cuspatial` docs builds to also run nightly (not just on PR merges only)

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Review by harrism — APPROVED** [review]
Thanks!

**Comment by AyodeAwe** [comment]
rerun tests

**Comment by harrism** [comment]
@AyodeAwe @ajschmidt8 is this ready to be merged for 23.06?

**Comment by AyodeAwe** [comment]
Monitoring this to get it merged today.

**Pull request merged**
