### PR TITLE
[REVIEW] Replace RMM get_default_resource with get_current_device_resource

### PR DESCRIPTION
**Pull request by trxcllnt**
Fixes compile errors using the latest RMM on branch-0.16. Similar to https://github.com/rapidsai/cudf/pull/6121.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by harrism — APPROVED** [review]

**Comment by trxcllnt** [comment]
rerun tests

**Comment by trxcllnt** [comment]
This is failing due to this:
```
$ git describe --tags
v0.15.0b-19-g848c397
```

**Comment by raydouglass** [comment]
rerun tests

**Comment by trxcllnt** [comment]
rerun tests

**Comment by kkraus14** [comment]
I'm going to push the conda recipe changes into this PR as well to try to fix the builds.

**Pull request merged**
