### PR TITLE
[FIX] NVCC warnings are errors

### PR DESCRIPTION
**Pull request by trxcllnt**
Make `nvcc` warnings into errors, fix new errors.

### CODE REVIEW

**Review by thomcom — APPROVED** [review]

**Review by cwharris — APPROVED** [review]

**Comment by trxcllnt** [comment]
rerun tests

**Comment by trxcllnt** [comment]
rerun tests

**Comment by trxcllnt** [comment]
rerun tests

**Comment by trxcllnt** [comment]
@gpucibot merge

**Pull request merged**
