### PR TITLE
Add symlink to `users.ipynb` for notebooks CI

### PR DESCRIPTION
**Pull request by thomcom**
## Description
This creates a symlink in `notebooks` so that @taureandyernv's notebooks CI can test it.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cuspatial/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by taureandyernv** [comment]
@thomcom , great work as always!  Can we rename the "User.ipynb" notebook in cuSpatial to "10 Minutes to CuSpatial" to align better with other intro notebooks naming conventions?

**Comment by harrism** [comment]
> @thomcom , great work as always! Can we rename the "User.ipynb" notebook in cuSpatial to "10 Minutes to CuSpatial" to align better with other intro notebooks naming conventions?

I think "10 minutes to cuspatial" is a different guide that we haven't written yet.  users.ipynb just provides a single simple example for every API in cuSpatial.

**Comment by thomcom** [comment]
I agree they're not the same thing at this time.

**Comment by taureandyernv** [comment]
okay, fair enough, then can we rename it from users to something more descriptive of what it is?

**Comment by harrism** [comment]
cuspatial_api_usage.ipynb ?

cuspatial_api_examples.ipynb ?

**Comment by taureandyernv** [comment]
`cuspatial_api_intro`?  `cuspatial_api_examples.ipynb` is also pretty apt.  But I name things like an engineer....

**Comment by harrism** [comment]
OK, how do we move this forward? I see two votes for `cuspatial_api_examples.ipynb`.

**Comment by taureandyernv** [comment]
Well, looks like the poll are closed!  @thomcom, may you rename the file and redo the symlink?

**Comment by thomcom** [comment]
Will do.

**Review by harrism — APPROVED** [review]

**Comment by harrism** [comment]
@gpucibot merge

**Pull request merged**
