### PR TITLE
[FEA] Enable discussions

### PR DESCRIPTION
**Pull request by jarmak-nv**
## Description
This PR removes the `Question` issue type and template in favor of using GitHub Discussions.  The new file, `config.yml`, adds a link in our discussions in the submit issue page so it works just like an issue template.

Reasoning
--
[QST] issues are largely inactionable and hard to act upon, it's better for us to discuss a question/comment/thought and then file a feature/bug/doc request as needed at the end of the conversation. It allows for free-form discussion and prevents the problem of 'when is a question done?' for closing the issue.

~This should not be merged until Discussions are enabled, so the https://github.com/rapidsai/cuspatial/labels/5%20-%20DO%20NOT%20MERGE label has been applied.~ (Thanks @raydouglass!)

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cuspatial/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by raydouglass — APPROVED** [review]

**Review by harrism — APPROVED** [review]

**Review by thomcom — APPROVED** [review]

**Comment by ajschmidt8** [comment]
@harrism, it looks like your `/merge` comment had some trailing whitespace which prevented it from working properly. I will re-comment.

**Comment by harrism** [comment]
I can't see any trailing whitespace, even if I click edit on my comment.

**Comment by ajschmidt8** [comment]
> I can't see any trailing whitespace, even if I click edit on my comment. Perhaps `/merge` should ignore trailing whitespace?

I saw some new lines when I clicked `Edit` on your comment.

But agreed. This is the second time this week that whitespace prevented a merge from working correctly.

Just pushed the commit below to trim whitespace from the merge comment. It will be deployed and take effect in a few minutes.

- https://github.com/rapidsai/ops-bot/commit/da0cfa7d326e8535ebfbc8015a5754cb17cb6310

**Comment by harrism** [comment]
Thanks!

**Pull request merged**
