### PR TITLE
Add `apply_boolean_mask` Feature

### LINKED ISSUE #927: [FEA]: Support boolean mask subsetting in GeoDataFrame/GeoSeries
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Critical (currently preventing usage)

### Please provide a clear description of problem you would like to solve.

Given a GeoDataFrame, I would like to do `df[[True, False, True, False]]` to subset the odd rows of the dataframe.

### Describe any alternatives you have considered

_No response_

### Additional context

Retrospectively added to track existing PR.

### PR DESCRIPTION
**Pull request by isVoid**
## Description

This PR makes geodataframe supports subsetting via boolean masks. closes #927 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cuspatial/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by thomcom** [comment]
I'm pretty sure that boolean masking already worked on `GeoSeries`, but I can see it not working for `GeoDataFrame`. Did you find a problem with that implementation? The additions to `GeoColumn` and `GeoSeries` may be duplication...

**Comment by isVoid** [comment]
You are right. They are supported by the iloc indexer. Removing.

**Review by thomcom — APPROVED** [review]

**Comment by isVoid** [comment]
Updated geodataframe implementation to depend on geoseries, not geocolumn.

**Review by harrism — APPROVED** [review]

**Pull request merged**
