### PR TITLE
address issue with vector equivalent utility

### LINKED ISSUE #772: [BUG] Issues with expect_vector_equivalent test utility
**Describe the bug**
1. We should move the header https://github.com/rapidsai/cuspatial/blob/branch-22.12/cpp/tests/utility/vector_equality.hpp to `include/cudf_test/vector_equality.hpp`
2. The call to `expect_vector_equivalent` in the macro here: https://github.com/rapidsai/cuspatial/blob/92c3a08c1ca87080cda8358ffd06693f04ffadba/cpp/tests/utility/vector_equality.hpp#L175 should be qualified with the namespace `cudf::test`. Also, unit tests should not be put inside that namespace, only test utilities.
3. The `setprecision()` calls should be changed to use the maximum decimal digits of the type being checked (`float` or `double`)
4. https://github.com/rapidsai/cuspatial/blob/92c3a08c1ca87080cda8358ffd06693f04ffadba/cpp/tests/utility/vector_equality.hpp#L60 this line should use `DoubleNear`, not `FloatNear`.

### PR DESCRIPTION
**Pull request by isVoid**
## Description

Closes #772 , Address various issue with vector equivalent utility.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cuspatial/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by thomcom** [comment]
rerun tests

**Comment by thomcom** [comment]
This needs passing tests.

**Comment by isVoid** [comment]
Ok I think it's fixed.

**Review by harrism — APPROVED** [review]

**Comment by isVoid** [comment]
rerun tests

**Comment by isVoid** [comment]
rerun tests

**Comment by isVoid** [comment]
@gpucibot merge

**Pull request merged**
