### PR TITLE
Switch to using public cudf testing utilities

### PR DESCRIPTION
**Pull request by vyasr**
As of rapidsai/cudf#7495 the `cudf.tests.utils` module (and in particular the `assert_eq` function) are no longer part of the public API. This PR switches tests to use the public testing functions in the `cudf.testing` subpackage.

This PR is currently blocked by #430 and rapidsai/cudf#8646.

### CODE REVIEW

**Comment by harrism** [comment]
@vyasr can we get this finished for 21.08?

**Comment by vyasr** [comment]
@harrism sure if you think it's worthwhile I can prioritize getting this done now, it shouldn't be too hard but just didn't seem to be a priority.

**Comment by harrism** [comment]
Is cuSpatial testing broken without this PR? If not, it can wait until 21.10.

**Comment by vyasr** [comment]
Testing isn't broken, it's just using some cudf functions that are not intended to be part of the API. We don't want cudf to have to maintain API stability for those functions since they're internal, so we need to remove their usage from here. I know this affects (at minimum) cugraph as well. Since we control these functions in cudf we can avoid making any breaking changes until other downstream packages stop using them, though, so I don't think this is urgent for this release.

That said, I've started trying to resolve these conflicts, so I can update here if finishing this for 21.08 will be feasible.

**Comment by vyasr** [comment]
@harrism I think this PR should be good to go if tests pass.

**Comment by vyasr** [comment]
Hmm [issues with the testing container](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cuspatial/job/prb/job/cuspatial-gpu-test/CUDA=11.0,GPU_LABEL=gpu-a100,LINUX_VER=centos7,PYTHON=3.7/54/console).

**Comment by vyasr** [comment]
rerun tests

**Review by cwharris — APPROVED** [review]

**Review by trxcllnt — APPROVED** [review]

**Comment by harrism** [comment]
@gpucibot merge

**Pull request merged**
