### PR TITLE
Build and test with CUDA 12.5.1

### PR DESCRIPTION
**Pull request by KyleFromNVIDIA**
This PR updates the latest CUDA build/test version 12.2.2 to 12.5.1.

Contributes to https://github.com/rapidsai/build-planning/issues/73

### CODE REVIEW

**Review by jameslamb — APPROVED** [review]

**Comment by jakirkham** [comment]
The notebook job appears to be hung. It has run for 3hrs without doing much. Before that it ran 6hrs and was finally terminated as it reached the CI time limit. Wondering if there is an issue with the notebook job that requires further independent investigation

Note: All other CI jobs have passed

**Comment by KyleFromNVIDIA** [comment]
https://github.com/rapidsai/cuspatial/pull/1399 is also having problems with the notebook tests

**Comment by jakirkham** [comment]
Think James is debugging PR: https://github.com/rapidsai/cuspatial/pull/1407

**Comment by jameslamb** [comment]
> *The notebook job appears to be hung. It has run for 3hrs without doing much.*

In logs here, it looks like it's stuck on the NYC taxi notebook.

```text
[NbConvertApp] Writing 7305 bytes to /tmp/nyc_taxi_years_correlation-test.py
```

In my interactive testing (on a machine with V100s, CUDA 12.2, and using RAPIDS 24.08 nightly conda packages), I also observed that notebook hanging for a long time. I'd hoped it was just something with my local setup 😭 

Specifically, this cell ran for 50 minutes before I killed it:

https://github.com/rapidsai/cuspatial/blob/c8616c1534f2555423186096cce156e6fd104ef7/notebooks/nyc_taxi_years_correlation.ipynb#L203-L219

Even when I reduced that for loop to `for i in range(2)` 😬 

I'll keep investigating over on #1407. This is blocking CI for `rapidsai/docker` as well.

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Comment by jakirkham** [comment]
All packages uploaded

**Pull request merged**
