### PR TITLE
[REVIEW] Use custom conda build directory for ccache

### PR DESCRIPTION
**Pull request by dillon-cullinan**
This changes the conda build directory to be a consistent directory when building packages. The resulting work directory from conda must be moved to a repo specific folder for project flash to work.

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Comment by dillon-cullinan** [comment]
rerun tests

**Review by ajschmidt8 — APPROVED** [review]

**Comment by dillon-cullinan** [comment]
rerun tests

**Comment by trxcllnt** [comment]
rerun tests

**Review by trxcllnt — APPROVED** [review]

**Comment by trxcllnt** [comment]
@dillon-cullinan seems like the failures are a 404 error. Any idea what's happening here?
```
requests.exceptions.HTTPError: 404 Client Error: None for url: file:///workspace/ci/artifacts/cuspatial/cpu/conda-bld/noarch/repodata.json
```

**Comment by trxcllnt** [comment]
rerun tests

**Comment by trxcllnt** [comment]
rerun tests

**Comment by dillon-cullinan** [comment]
Looks like these failures are build related, will need diagnosis from a dev.

**Comment by trxcllnt** [comment]
@dillon-cullinan does the CI runner not pull `branch-0.20` into this PR before building? These should be resolved by merging in the latest in `branch-0.20`.

**Comment by dillon-cullinan** [comment]
It should. If there are no merge conflicts, CI should use the merge commit hash and no my branch hash. I'll still update though.

**Comment by trxcllnt** [comment]
Now seems we're blocked by the issue fixed in https://github.com/rapidsai/cuspatial/pull/384 :sweat_smile:

**Comment by trxcllnt** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
@gpucibot merge

**Pull request merged**
