### PR TITLE
clustering notebook added in  python/cuspatial/notebooks/clustering_with_cuspatial/ directory

### PR DESCRIPTION
**Pull request by wkelongws**
Create a notebooks folder in python/cuspatial/ and added clustering_with_cuspatial in that folder

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by kkraus14** [comment]
add to whitelist

**Comment by thomcom** [comment]
I added a CHANGELOG entry for you @wkelongws

**Comment by thomcom** [comment]
I heard @harrism wants this in the `notebooks` repository. Makes sense.

**Comment by wkelongws** [comment]
> I heard @harrism wants this in the `notebooks` repository. Makes sense.

what is the right place to put this notebook in? right now it is on https://github.com/wkelongws/trajectory_clustering_with_cuspatial and linked in the blog. Would this merge be a blocker for the blog?

**Comment by thomcom** [comment]
@harrism are we going to enforce this afternoon that all notebooks go into the github.com/rapidsai/notebooks or `-extended` repository?

**Comment by harrism** [comment]
I checked, and @kkraus14 said this needs to move to the https://github.com/rapidsai/notebooks repo. Please open a PR there.

**Comment by harrism** [comment]
> > I heard @harrism wants this in the `notebooks` repository. Makes sense.
> 
> what is the right place to put this notebook in? right now it is on https://github.com/wkelongws/trajectory_clustering_with_cuspatial and linked in the blog. Would this merge be a blocker for the blog?

If you don't have time, I will create the PR now.

**Comment by harrism** [comment]
Note that notebooks are self documenting. They should not have extra README files -- just put the contents of the readme in the notebook. :)

**Comment by harrism** [comment]
Moved to rapidsai/notebooks. Closing.

**Pull request closed without merging**
