### PR TITLE
[REVIEW] Pin gdal to be compatible with cuxfilter

### PR DESCRIPTION
**Pull request by raydouglass**
`cuxfilter` has a dependency on `geopandas` which seems to be locked to `gdal` 3.0.x.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
Not sure why that pulled gdal `3.1.0` with the spec of `>=3.0.2,<3.1.0a`

**Comment by mike-wendt** [comment]
> Not sure why that pulled gdal `3.1.0` with the spec of `>=3.0.2,<3.1.0a` - retrying the builds
Figure this out, needed to merge rapidsai/integration#53 and rebuild updated env pkgs - this is done now and should pass

**Comment by raydouglass** [comment]
rerun tests

**Comment by mike-wendt** [comment]
Should be GTG now with the above commit

**Comment by harrism** [comment]
I would like @thomcom to approve before merging.

**Pull request merged**
