### PR TITLE
[BUG] Added flag to not treat deprecation warnings as errors, for now.

### PR DESCRIPTION
**Pull request by thomcom**
Added flag to not treat deprecation warnings as errors, for now. This will likely be removed when the RMM API calls have been updated for 0.14.

### CODE REVIEW

**Comment by kkraus14** [comment]
@thomcom I believe you also need to add it to the `CMAKE_CUDA_FLAGS`

**Comment by thomcom** [comment]
Done.``

**Comment by kkraus14** [comment]
rerun tests

**Comment by harrism** [comment]
rerun tests

**Comment by thomcom** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Comment by thomcom** [comment]
rerun tests

**Comment by kkraus14** [comment]
Good find @thomcom!

**Pull request merged**
