### PR TITLE
 Fix `assert_eq` related imports

### PR DESCRIPTION
**Pull request by galipremsagar**
Recently there has been a change of location of where the testing utils of cudf reside. This PR is adapting to those changes.

reference: rapidsai/cudf#7495

### CODE REVIEW

**Comment by vyasr** [comment]
@galipremsagar if you don't mind I'll post a new PR tomorrow superseding this one. As discussed on Slack (thread with @shwina and others) non-cudf packages should be avoiding the use of `assert_eq`.

**Comment by vyasr** [comment]
rerun tests

**Comment by vyasr** [comment]
In light of rapidsai/cudf#8646, disregard my previous comment for now. Let's get this PR merged to unblock further development. I have the other changeset ready and will push those changes once the cudf testing issue is resolved.

Note that tests on this PR will not pass until the issue causing #427 is fixed, but we'll be stuck without merging at least one of them first and this one is finished.

**Review by thomcom — APPROVED** [review]

**Review by cwharris — APPROVED** [review]

**Comment by cwharris** [comment]
Closing per @vyasr 's comment. Will merge this work into #430 so we can get one PR to fix cuspatial.

**Pull request closed without merging**
