### PR TITLE
[REVIEW] quadtree indexing for point data and point-in-polygon based indexed spatial join

### PR DESCRIPTION
**Pull request by zhangjianting**
1. Please write a description in this text box of the changes that are being
   made.
Implementing bottom-up quadtree construction algorithm described at Efficient Quadtree Construction for Indexing Large-Scale Point Data on GPUs 

Please spare the debug info in the code (both src and tests) during the first round of code review. They are needed to ensure correctness during changes based on code review feedbacks. They can be easily removed during the last stage of code review process.   

There are four modules in this PR:
bottom-up quadtree indexing on point data (src/indexing/quadtree.cu)
computing bounding boxes for polygons (src/spatial/bounding_box.cu)
spatial filtering based on intersection test of quadrants and polygon bounding boxes (src/join/quadtree_polygon.cu)
spatial refinement based on point-in-polygon test for all points in a quadrant and a polygon (src/join/pip_refine.cu)

2. Please ensure that you have written units tests for the changes made/features
  Each module has 2-4 tests. There is also a comprehensive test using NYC taxi trip data for end-to-end spatial join.

### CODE REVIEW

**Comment by zhangjianting** [comment]
There are four modules in this PR: 
1) bottom-up quadtree indexing on point data (src/indexing/quadtree.cu)
2) computing bounding boxes for polygons (src/spatial/bounding_box.cu)
3) spatial filtering based on intersection test of quadrants and polygon bounding boxes (src/join/quadtree_polygon.cu)
4) spatial refinement based on point-in-polygon test for all points in a quadrant and a polygon (src/join/pip_refine.cu)
A brief documentation on design/implementation will be added later.

**Comment by thomcom** [comment]
Is this ready for review? Or were you thinking I should add my python bindings directly to your branch?

**Comment by zhangjianting** [comment]
> Is this ready for review? Or were you thinking I should add my python bindings directly to your branch?

Likely there will be additional changes of the code due to issues that might happen when testing on large-scale data. But I think you can start with Python APIs, ideally to have a demo at GTC.

**Comment by zhangjianting** [comment]
rerun

**Comment by zhangjianting** [comment]
rerun

**Comment by zhangjianting** [comment]
rerun

**Comment by thomcom** [comment]
rerun tests

**Comment by zhangjianting** [comment]
rerun tests

**Comment by zhangjianting** [comment]
rerun tests

**Comment by zhangjianting** [comment]
Based on our meeting today (03/25/2020), I am going to split this PR into 4 PRs.

**Pull request closed without merging**
