### PR TITLE
[REVIEW] Fix branch-0.15 conda dev environment dependencies

### PR DESCRIPTION
**Pull request by trxcllnt**
* Update cuDF to 0.15
* Inherit black, flake8, and isort versions from cudf

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by ajschmidt8** [comment]
@trxcllnt, should this PR be targeting `branch-0.16` instead of `branch-0.15`?

**Comment by trxcllnt** [comment]
> @trxcllnt, should this PR be targeting `branch-0.16` instead of `branch-0.15`?

Oh yeah I originally intended to target 0.16. But this is also a problem in 0.15 now, so if we change the cudf version to 0.15, we can target 0.15.

**Comment by trxcllnt** [comment]
@ajschmidt8 Ok, updated PR so we can target branch-0.15

**Comment by trxcllnt** [comment]
Made a new PR from branch-0.15 here: https://github.com/rapidsai/cuspatial/pull/267

**Pull request closed without merging**
