### PR TITLE
Python User's Guide

### PR DESCRIPTION
**Pull request by thomcom**
In process.

Contributes to #599

### CODE REVIEW

**Comment by isVoid** [comment]
Would it be better to place the dev docs in rapids documentation along side with API reference for better visibility?

**Comment by thomcom** [comment]
What do you mean?

**Comment by vyasr** [comment]
Michael is asking whether this documentation should be placed inside `docs/source` so that it can be compiled along with the Sphinx documentation and made visible online, as opposed to being put in a file like this one that will only be visible if someone navigates to it on their local filesystem or on GH.

In cudf the C++ documentation is all like this, whereas [the Python developer docs are published](https://docs.rapids.ai/api/cudf/nightly/developer_guide/index.html). FWIW I would eventually like to get all of them published somewhere, but I have not put much thought or effort into making that happen yet. If you all come up with a solution in for cuspatial I would love to hear it.

CC @harrism who I think wrote most of the libcudf docs originally in case he has thought about this before.

**Comment by harrism** [comment]
This is Python docs, so should be in docs/source just like they are in cuDF. (That's what I suggested in #599).

I agree the C++ docs should also be rendered into HTML, but I have never implemented that myself.

**Comment by thomcom** [comment]
Closing in favor of #666.

**Pull request closed without merging**
