### PR TITLE
Refactors `bounding.py` to accept GeoSeries Input

### LINKED ISSUE #929: Convert `Polygon Bounding Boxes` to Accept GeoSeries as Input

### LINKED ISSUE #930: Convert `LineString Bounding Boxes` to Accept GeoSeries as Input

### PR DESCRIPTION
**Pull request by isVoid**
## Description

This PR refactors `[polygon|linestring]_bounding_boxes` API to accept geoseries input.
closes #929 closes #930

depends on #928

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cuspatial/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by isVoid** [comment]
I have also decided to work on the user guide notebook as a finishing item after I finished working on all the geoseries refactor due to the large git diff every time I work on one.

**Review by harrism — APPROVED** [review]
Does the users.ipynb need to be updated for all these API changing PRs? Otherwise looks good.

**Comment by isVoid** [comment]
> Does the users.ipynb need to be updated for all these API changing PRs? Otherwise looks good.

Yes, decided to do that as a separate effort, tracked by https://github.com/rapidsai/cuspatial/issues/935

**Review by thomcom — APPROVED** [review]

**Review by harrism — APPROVED** [review]

**Pull request merged**
