### PR TITLE
replace `ccache` with `sccache`

### PR DESCRIPTION
**Pull request by AyodeAwe**
This PR replaces `ccache` with `sccache`

### CODE REVIEW

**Comment by ajschmidt8** [comment]
pre-cache C++ build time ([log link](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cuspatial/job/prb/job/cuspatial-cpu-cuda-build/184/CUDA=11.5/consoleFull)): 0:11:48.2

image

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
PR is ready for review, but we'll wait to merge until all the other PRs are confirmed working as well.

**Review by ajschmidt8 — COMMENTED** [review]
@AyodeAwe, can you update this last `ccache` reference to say `sccache`?

- https://github.com/rapidsai/cuspatial/blob/branch-22.04/cpp/cmake/Modules/ConfigureCUDA.cmake#L25

**Review by ajschmidt8 — APPROVED** [review]

**Review by trxcllnt — APPROVED** [review]

**Comment by ajschmidt8** [comment]
@gpucibot merge

**Comment by harrism** [comment]
@ajschmidt8 What was the post sccache build time on this one?

**Comment by ajschmidt8** [comment]
> @ajschmidt8 What was the post sccache build time on this one?

47s!

image

**Pull request merged**
