### PR TITLE
[REVIEW] Upgrade `clang` to `11.1.0`

### PR DESCRIPTION
**Pull request by galipremsagar**
This upgrade is required to be in-line with: rapidsai/cudf#9716

Depends on: rapidsai/integration#390

### CODE REVIEW

**Review by raydouglass — APPROVED** [review]

**Review by harrism — APPROVED** [review]

**Comment by harrism** [comment]
I guess this won't pass until CI version of clang-format is upgraded. 

```
>>>> FAILED: clang format check; begin output
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
Traceback (most recent call last):
  File "cpp/scripts/run-clang-format.py", line 142, in <module>
    main()
  File "cpp/scripts/run-clang-format.py", line 118, in main
    args = parse_args()
  File "cpp/scripts/run-clang-format.py", line 66, in parse_args
    (EXPECTED_VERSION, version))
Exception: clang-format exe must be v11.1.0 found '11.0.0'
>>>> FAILED: clang format check; end output
```

**Comment by galipremsagar** [comment]
> I guess this won't pass until CI version of clang-format is upgraded.
> 
> ```
> >>>> FAILED: clang format check; begin output
> /bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
> Traceback (most recent call last):
>   File "cpp/scripts/run-clang-format.py", line 142, in <module>
>     main()
>   File "cpp/scripts/run-clang-format.py", line 118, in main
>     args = parse_args()
>   File "cpp/scripts/run-clang-format.py", line 66, in parse_args
>     (EXPECTED_VERSION, version))
> Exception: clang-format exe must be v11.1.0 found '11.0.0'
> >>>> FAILED: clang format check; end output
> ```

Yes Mark, that's correct. The CI changes https://github.com/rapidsai/integration/pull/390 have been merged but will likely take some time for new images to be out

**Comment by galipremsagar** [comment]
rerun tests

**Comment by galipremsagar** [comment]
@gpucibot merge

**Pull request merged**
