### PR TITLE
Fix style checks.

### PR DESCRIPTION
**Pull request by bdice**
## Description
Fixes issues seen in #788.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cuspatial/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by thomcom — APPROVED** [review]

**Comment by bdice** [comment]
@harrism @thomcom Can someone with privileges merge this?

**Review by raydouglass — APPROVED** [review]

**Comment by raydouglass** [comment]
@gpucibit merge

**Comment by raydouglass** [comment]
@gpucibot merge

**Comment by thomcom** [comment]
Thanks @bdice!

**Pull request merged**
