### PR TITLE
Move spatial_window_points/query.hpp to legacy

### PR DESCRIPTION
**Pull request by harrism**
This is the first step in #157 , simply moving the old files to legacy folders.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by trxcllnt** [comment]
Looks like CI is failing because this line in the Cython needs to change to `legacy/query.hpp`:
https://github.com/rapidsai/cuspatial/blob/55311bf5b42bb5c0ef454299d3dd5c16f38c81e6/python/cuspatial/cuspatial/_lib/spatial.pxd#L31

**Comment by harrism** [comment]
> How come the cu files don't show up as a move?

No idea. Probably moved it in vscode rather than git. Sorry.

**Comment by cwharris** [comment]
@harrism I move all my files in vscode by drag-and-drop. 🤷🏻‍♂️

Sometimes I wish I knew git better... Sometimes.

**Pull request merged**
