### PR TITLE
split up CUDA-suffixed dependencies in dependencies.yaml

### PR DESCRIPTION
**Pull request by jameslamb**
## Description

Contributes to https://github.com/rapidsai/build-planning/issues/31

In short, RAPIDS DLFW builds want to produce wheels with unsuffixed dependencies, e.g. `cudf` depending on `rmm`, not `rmm-cu12`.

This PR is part of a series across all of RAPIDS to try to support that type of build by setting up CUDA-suffixed and CUDA-unsuffixed dependency lists in `dependencies.yaml`.

For more details, see:
* https://github.com/rapidsai/build-planning/issues/31#issuecomment-2245815818
* https://github.com/rapidsai/cudf/pull/16183

### Why target 24.08?

This is targeting 24.08 because:

1. it should be very low-risk
2. getting these changes into 24.08 prevents the need to carry around patches for every library in DLFW builds using RAPIDS 24.08

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cuspatial/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by jameslamb** [comment]
These tests are failing, for both wheels and conda packages, with dozens of errors like this:

> FAILED tests/binpreds/test_contains_properly.py::test_point_in_polygon[point14-polygon14-True] - ValueError: All data.values() must be Column, not Series

([build link](https://github.com/rapidsai/cuspatial/actions/runs/10070858308/job/27840492293?pr=1414))

I strongly suspect that's related to some recent change in `cudf`, and not the changes in this PR.

**Comment by jameslamb** [comment]
I've updated this based on the suggestions from https://github.com/rapidsai/cudf/pull/16183.

Ran the following to check `update-version.sh`.

```shell
git fetch upstream --tags
ci/release/update-version.sh '24.10.00'

git grep -E '24\.8|24\.08'
```

**Comment by jameslamb** [comment]
> *I strongly suspect that's related to some recent change in cudf, and not the changes in this PR.*

@mroeschke confirmed offline that these failing tests are unrelated to this PR's changes, and this is safe to admin-merge.

**Comment by jameslamb** [comment]
Cancelling CI here (and will on other commits in the next 24 hours) to save some CI capacity for other projects that are about to enter code freeze.

**Review by vyasr — APPROVED** [review]

**Pull request merged**
