### PR TITLE
[REVIEW] upgrade thrust to latest commit

### PR DESCRIPTION
**Pull request by rongou**
This is to make it consistent with cuDF: https://github.com/rapidsai/cudf/blob/branch-0.16/thirdparty/CMakeLists.txt

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by harrism** [comment]
As discussed on RMM, shouldn't fetching Thrust get CUB via recursive submodule fetch?

**Comment by rongou** [comment]
@harrism done.

**Review by harrism — APPROVED** [review]

**Comment by trxcllnt** [comment]
rerun tests

**Comment by trxcllnt** [comment]
ok to test

**Comment by harrism** [comment]
rerun tests

**Comment by trxcllnt** [comment]
@harrism I think we're going to see CI issues across all repos until https://github.com/rapidsai/rmm/pull/542 and https://github.com/rapidsai/integration/pull/123 are merged. I'm seeing `fmt` related build errors in https://github.com/rapidsai/cuspatial/pull/287 and other cuDF PRs.

**Comment by rongou** [comment]
rerun tests

**Comment by kkraus14** [comment]
rerun tests

**Comment by harrism** [comment]
Still not getting the right spdlog...

**Comment by kkraus14** [comment]
Doesn't look like spdlog anymore: ```
/var/lib/jenkins/workspace/rapidsai/gpuci/cuspatial/prb/cuspatial-gpu-build/cpp/include/cuspatial/polygon_bounding_box.hpp(45): error: namespace "rmm::mr" has no member "get_default_resource"```

**Comment by kkraus14** [comment]
rerun tests

**Review by kkraus14 — APPROVED** [review]

**Comment by harrism** [comment]
@kkraus14 related to get_default_resource: not sure why it's getting that error since the functions are only deprecated, probably because they are now in a header that's not automatically included. But in any case this PR should fix that: https://github.com/rapidsai/cuspatial/pull/287

**Comment by kkraus14** [comment]
I pushed a conda recipe change that did in fact make the solver prioritize getting a newer rmm version over the spdlog version so once your fix is merged we should be good to go here.

**Comment by kkraus14** [comment]
rerun tests

**Pull request merged**
