### PR TITLE
[WIP] Problem importing libgdal

### LINKED ISSUE #275: [BUG] ImportError: libgdal.so.26: cannot open shared object file: No such file or directory in nightly container
**Describe the bug**
When importing `cuspatial` I got this ImportError: libgdal.so.26: cannot open shared object file: No such file or directory in nightly container.

**FULL TRACE**

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-aa33e033382d> in <module>
      1 import cudf
----> 2 import cuspatial
      3 from collections import OrderedDict
      4 import numpy as np
      5 import datetime as dt

/opt/conda/envs/rapids/lib/python3.7/site-packages/cuspatial/__init__.py in <module>
----> 1 from .core import interpolate
      2 from .core.gis import (
      3     directed_hausdorff_distance,
      4     haversine_distance,
      5     lonlat_to_cartesian,

/opt/conda/envs/rapids/lib/python3.7/site-packages/cuspatial/core/interpolate.py in <module>
      6 from cudf import DataFrame, Series
      7 
----> 8 from cuspatial._lib.interpolate import (
      9     cubicspline_coefficients,
     10     cubicspline_interpolate,

ImportError: libgdal.so.26: cannot open shared object file: No such file or directory
```

**Steps/Code to reproduce bug**
`import cuspatial` should load the library.

**Expected behavior**
Should load the library.

**Environment details (please complete the following information):**
 - Environment location: Docker
 - Method of cuSpatial install: Docker
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

   -- **PULL**: docker pull rapidsai/rapidsai-nightly:cuda10.2-runtime-ubuntu18.04-py3.7
   -- **RUN**:

```
docker run --gpus all -it -p 8888:8888 -p 8787:8787 -p 8786:8786 --name kdd_rapids \
	rapidsai/rapidsai-nightly:cuda10.2-runtime-ubuntu18.04-py3.7
```
 

**Additional context**

### PR DESCRIPTION
**Pull request by thomcom**
This may fix #275. I can't test it directly but instead will just see how the next nightly works out. There's a problem with libgdal.so in the nightly docker containers. This change makes the gdal requirements for building from source match the requirements of the conda installation - hopefully this will resolve the issue?

@kkraus14 maybe you have an idea behind what is causing #275? Think this will help?

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by kkraus14** [comment]
This won't effect end user environment. It has to be something in a conda recipe that isn't properly constraining the `libgdal` / `gdal` version.

**Comment by thomcom** [comment]
There are two conda recipes in cuspatial: `recipes/cuspatial/meta.yaml` and `recipes/libcuspatial/meta.yaml`. Both are specified with `- gdal >=3.0.2,<3.1.0a0`, which is especially strange since the version of gdal installed in the nightly docker container is `3.1.2`

**Comment by thomcom** [comment]
@trxcllnt suggested there is an ops repository responsible for the docker build configuration?

**Comment by kkraus14** [comment]
Version is already constrained there appropriately: https://github.com/rapidsai/integration/blob/branch-0.15/conda/recipes/versions.yaml#L66-L67

Only other thought is maybe an outdated docker image is being used?

**Comment by thomcom** [comment]
`docker pull rapidsai/rapidsai-nightly:cuda10.2-runtime-ubuntu18.04-py3.7` doesn't seem to be.

**Comment by harrism** [comment]
For PRs, please use [WIP] for work in progress, [REVIEW] for review. (At least until github shows labels in notifications page).

**Comment by kkraus14** [comment]
> `docker pull rapidsai/rapidsai-nightly:cuda10.2-runtime-ubuntu18.04-py3.7` doesn't seem to be.

You confirmed the same problem in pulling the latest docker image?

**Comment by trxcllnt** [comment]
I'll test this in a container later this afternoon too.

A while back we started getting weird errors after some gdal recipe change. Sometimes it works if you make a new conda env, or only install cuspatial.

It's possible people only see this when another package depends on a gdal version before (or after?) this change.

**Comment by thomcom** [comment]
Yeah it continues to exist in the latest nightly.

**Comment by trxcllnt** [comment]
@thomcom Looks like this is missing a changelog entry. I'm in favor of this since it more closely matches the integration repo's `meta.yml`, though I don't think it'll fix #275, since these files aren't considered when installing from conda.

**Pull request closed without merging**
