### PR TITLE
[WIP] Code to run benchmarks

### PR DESCRIPTION
**Pull request by Salonijain27**

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by Salonijain27** [comment]
Updating the code to use rapids benchmark library (https://github.com/rapidsai/benchmark)

**Comment by thomcom** [comment]
Moved to 0.19

**Comment by ajschmidt8** [comment]
Removing `ops-codeowners` from the required reviews since it doesn't seem there are any file changes that we're responsible for. Feel free to add us back if necessary.

**Pull request closed without merging**
