### PR TITLE
[REVIEW] Add cudf example code for haversine distance into 23.10

### PR DESCRIPTION
**Pull request by taureandyernv**
Supersedes https://github.com/rapidsai/cuspatial/pull/1259
Created a cudf -> cuspatial example for haversine distance in the docs
Added example code to the api docs with some explanation on benefits of this method

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cuspatial/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by taureandyernv** [comment]
morning @harrism!  Those commits had been sitting completed since your suggestions as I have been looking for time to spin up a new instance to remove the warnings.  Give me a bit to get those "warning removed" commits in and we should be complete by EOD tomorrow.

**Comment by harrism** [comment]
OK thanks @taureandyernv . if you want CI to run you will need to either do `/ok to test` after each push or rebase as described above.

**Review by harrism — APPROVED** [review]
Thanks @taureandyernv !

**Pull request merged**
