### PR TITLE
Use thrust::host_vector instead of std::vector<bool> in tests

### LINKED ISSUE #823: Avoid `vector<bool>`, use `thrust::host_vector<bool>` instead.
In tests where you compare against device data, just use a `thrust::device_vector` or `thrust::host_vector`.

_Originally posted by @harrism in https://github.com/rapidsai/cuspatial/pull/750#discussion_r1016004573_

### PR DESCRIPTION
**Pull request by cwharris**
## Description
Updates tests to use `thrust::host_vector<bool>` instead of `std::vector<bool>` and in one case `std::vector<int>` where int was logically bool.

closes #823

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cuspatial/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by cwharris** [comment]
Another way we could do this is by creating a `host_vector_converter` class that has an implicit `initializer_list` constructor and an implicit `thrust::host_vector` conversion operator, eliminating the need to call a function.

**Review by isVoid — APPROVED** [review]

**Comment by isVoid** [comment]
> Another way we could do this is by creating a host_vector_converter class that has an implicit initializer_list constructor and an implicit thrust::host_vector conversion operator, eliminating the need to call a function.

I'm curious how this is done. Wouldn't you still need to call `host_vector_converter` ctor somewhere to resolve to the conversion operator?

**Comment by cwharris** [comment]
@isVoid Yes, you're right. We would have to modify the function signatures or explicitly call the converter constructor. I didn't think this through properly.

**Pull request merged**
