### PR TITLE
Update Cython Table APIs to match changes in cudf.

### PR DESCRIPTION
**Pull request by vyasr**
This makes cuspatial compatible with the changes in rapidsai/cudf#9199.

### CODE REVIEW

**Comment by vyasr** [comment]
This should not be merged until after the rapidsai/cudf#9199.

**Comment by vyasr** [comment]
rerun tests

**Comment by vyasr** [comment]
rerun tests

**Comment by jakirkham** [comment]
rerun tests

**Review by thomcom — APPROVED** [review]
lgtm

**Comment by vyasr** [comment]
It looks like we also need to update cuspatial for #9011. I'll lump those changes into this PR as well.

**Comment by vyasr** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
Thank you Vyas! 😄

**Pull request merged**
