### PR TITLE
Update to GCC 11

### PR DESCRIPTION
**Pull request by bdice**
This PR updates builds to use GCC 11.

### CODE REVIEW

**Review by harrism — APPROVED** [review]

**Comment by bdice** [comment]
There are a few missing headers, like `<optional>` here:

```
sccache $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++ -DFMT_HEADER_ONLY=1 -DFMT_SHARED -DGTEST_LINKED_AS_SHARED_LIBRARY=1 -DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_INFO -DSPDLOG_FMT_EXTERNAL -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA -DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP -I$SRC_DIR/cpp -I$SRC_DIR/cpp/src -I$PREFIX/include/rapids/libcudacxx -I$PREFIX/include/libcudf/rapids -I$SRC_DIR/cpp/include -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/libcuspatial-split- -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -isystem /usr/local/cuda/include -O3 -DNDEBUG -fPIE -Wall -Werror -Wno-unknown-pragmas -Wno-error=deprecated-declarations -Wno-deprecated-declarations -pthread -MD -MT tests/CMakeFiles/POINT_DISTANCE_TEST.dir/spatial/point_distance_test.cpp.o -MF tests/CMakeFiles/POINT_DISTANCE_TEST.dir/spatial/point_distance_test.cpp.o.d -o tests/CMakeFiles/POINT_DISTANCE_TEST.dir/spatial/point_distance_test.cpp.o -c $SRC_DIR/cpp/tests/spatial/point_distance_test.cpp
In file included from $SRC_DIR/cpp/tests/spatial/point_distance_test.cpp:17:
$SRC_DIR/cpp/include/cuspatial/distance/point_distance.hpp:38:8: error: 'optional' is not a member of 'std'
   38 |   std::optional<cudf::device_span<cudf::size_type const>> multipoints1_offset,
      |        ^~~~~~~~
$SRC_DIR/cpp/include/cuspatial/distance/point_distance.hpp:20:1: note: 'std::optional' is defined in header '<optional>'; did you forget to '#include <optional>'?
   19 | #include <cudf/column/column_view.hpp>
  +++ |+#include <optional>
   20 | 
```
https://github.com/rapidsai/cuspatial/actions/runs/4297827595/jobs/7491314527#step:6:921

**Comment by harrism** [comment]
linestring_distance seems to be missing <optional> too. Possibly others.

**Comment by isVoid** [comment]
I was trying to reproduce the environment following https://docs.rapids.ai/resources/reproducing-ci/ . I was able to reproduce the environment but the local changes I made on top of the existing commit wasn't taken into effect with `./ci/build_cpp.sh`. Did I do anything wrong?

**Comment by isVoid** [comment]
The failure seems has to do with https://github.com/rapidsai/cuspatial/pull/964. But that PR's CI is also failing. We have a deadlock here... @galipremsagar can you also push the fixes to this PR?

**Comment by isVoid** [comment]
rerun tests

**Review by jjacobelli — APPROVED** [review]

**Pull request merged**
