### PR TITLE
Add binary_predicates.ipynb workflow and test data to package.

### PR DESCRIPTION
**Pull request by thomcom**
## Description
A missing package in this notebook is required in order for it to be usable with 23.08.

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cuspatial/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Review by isVoid — COMMENTED** [review]
I didn't see the `testing` package included.

**Comment by harrism** [comment]
Targeting 23.10 now.

**Comment by thomcom** [comment]
Retargeted 23.10 and added the missing `testing` package.

**Comment by harrism** [comment]
Can you change the title of this PR so it doesn't sound like we are enabling something that doesn't work in this release?

**Comment by thomcom** [comment]
Thanks for shepherding this across the finish line, @harrism

**Review by harrism — APPROVED** [review]
Thanks @thomcom !

**Pull request merged**
