### PR TITLE
Initialize a `GeoDataFrame` with `dict`.

### PR DESCRIPTION
**Pull request by thomcom**
This PR adds support for intializing a `GeoDataFrame` from a `dict` of type `list` or `GeoSeries`.

Closes https://github.com/rapidsai/cuspatial/issues/688

### CODE REVIEW

**Review by isVoid — APPROVED** [review]

**Comment by thomcom** [comment]
rerun tests

**Comment by thomcom** [comment]
@harrism do you mind posting an approve?

**Comment by thomcom** [comment]
@harrism do you mind reviewing?

**Comment by thomcom** [comment]
@gpucibot merge

**Pull request merged**
