### PR TITLE
Initiate cuspatial java layer binding [skip ci]

### PR DESCRIPTION
**Pull request by byin001**

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by kkraus14** [comment]
ok to test

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by thomcom** [comment]
@byin001 Add an update to CHANLOG.md with the PR number (#288) and a quick note about the addition.

Thanks!

**Comment by harrism** [comment]
> @byin001 Add an update to CHANLOG.md with the PR number (#288) and a quick note about the addition.
> 
> Thanks!

Should go under release 0.16 under the "New Features" heading.

**Comment by byin001** [comment]
> > @byin001 Add an update to CHANLOG.md with the PR number (#288) and a quick note about the addition.
> > Thanks!
> 
> Should go under release 0.16 under the "New Features" heading.

As instructed, I merged branch-0.16 to my start branch main.

**Comment by byin001** [comment]
> @byin001 Add an update to CHANLOG.md with the PR number (#288) and a quick note about the addition.
> 
> Thanks!

**Review by mike-wendt — APPROVED** [review]
Approved for changes in our codeowners files

**Comment by byin001** [comment]
PR src branch should not be based off byin001:main, which is forked from rapidsai:main and rapidsai:branch-0.16 merged. Need to redo the PR with src branch only consists of commits of mine and rapidsai:branch-0.16

**Pull request closed without merging**
