### PR TITLE
Build cuspatial with scikit-build

### PR DESCRIPTION
**Pull request by vyasr**
This PR switches cuspatial's Python build system to use scikit-build and CMake.

### CODE REVIEW

**Comment by vyasr** [comment]
This PR depends on https://github.com/rapidsai/rapids-cmake/pull/189, but once that's merged I think we should be good to go here.

**Comment by vyasr** [comment]
rerun tests

**Review by harrism — APPROVED** [review]
Thanks @vyasr !

**Comment by vyasr** [comment]
@gpucibot merge

**Pull request merged**
