### PR TITLE
Bump isort, enable Cython package resorting

### PR DESCRIPTION
**Pull request by charlesbluca**
With rapidsai/integration#286, the version of `isort` running on gpuCI will be bumped to 5.6.4, allowing us to enforce the sorting of packages in Cython (pyx, pxd) files. This PR intends to:

- Enable these checks in the gpuCI style script
- Enable Cython package resorting in the pre-commit hook
- Resort all the Cython files in this repo so they pass the newly enabled checks

These checks are optional, meaning that even without this being merged, gpuCI should still pass on style checks even when rapidsai/integration#286 is merged.

### CODE REVIEW

**Review by thomcom — APPROVED** [review]

**Comment by charlesbluca** [comment]
Looks like the style failures here are in Black - this might be because pre-commit is using `stable` while gpuCI is using `19,10`

**Comment by charlesbluca** [comment]
rerun tests

**Comment by charlesbluca** [comment]
rerun tests

**Review by ajschmidt8 — APPROVED** [review]
Approving `ops-codeowner` file changes

**Comment by ajschmidt8** [comment]
@gpucibot merge

**Pull request merged**
