### PR TITLE
add units to haversine distance docstring

### LINKED ISSUE #137: [DOC] Unit of haversine distance in haversine.cu
## Report incorrect documentation

**Location of incorrect documentation**
haversine.cu

**Describe the problems or issues found in the documentation**
It is not clear what the unit is for the haversine distance. 

**Steps taken to verify documentation is incorrect**
Read all the code.

**Suggested fix for documentation**
Could you please clarify it and maybe add a comment to the code?

---

### PR DESCRIPTION
**Pull request by bandersen23**
Since the units returned are in kilometers, I added that to the docstring so it appears in documentation. Closes #137.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by harrism** [comment]
ok to test

**Comment by harrism** [comment]
Thanks for the doc fix @bandersen23 ! Seems your change caused a style check failure (line too long):

```
python/cuspatial/cuspatial/core/gis.py:100:80: E501 line too long (85 > 79 characters)
```

**Review by harrism — APPROVED** [review]

**Comment by bandersen23** [comment]
Thanks @harrism! I just fixed the style check failures 👍

**Comment by harrism** [comment]
Since this is a doc-only change and it is passing, I think one approval is sufficient. @gpucibot merge

**Comment by harrism** [comment]
@gpucibot merge

**Pull request merged**
