### PR TITLE
Add documentation for `pairwise_linestring_polygon_distance`, `pairwise_polygon_distance`

### LINKED ISSUE #1146: [DOC]: linestring-polygon and polygon-polygon distance missing user example
### How would you describe the priority of this documentation request

Medium

### Is this for new documentation, or an update to existing docs?

New

### Describe the incorrect/future/missing documentation

In `cuspatial_api_example`, `pairwise_linestring_polygon_distance` and `pairwise_polygon_distance` are missing their example. Should be added before release 23.06.

### If this is a correction, please provide a link to the incorrect documentation. If this is a new documentation request, please link to where you have looked.

_No response_

### PR DESCRIPTION
**Pull request by isVoid**
## Description

closes #1146

Add missing API examples for 23.06 release.

 - Added example for `pairwise_linestring_polygon_distance`, `pairwise_polygon_distance`

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cuspatial/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by harrism — APPROVED** [review]

**Review by jarmak-nv — APPROVED** [review]
At some point we should resolve the `FutureWarning` on the Natural Earth dataset, but low prio until GeoPandas 1.0 has a set date.

**Comment by harrism** [comment]
```
Warning, treated as error:
/__w/cuspatial/cuspatial/docs/source/user_guide/cuspatial_api_examples.ipynb:653:image file not readable: user_guide/attachment:8c5d8b90-2241-45c2-b98c-20d48d1ee6b7.png
```

**Review by ajschmidt8 — APPROVED** [review]
Approving `ops-codeowner` file changes

**Pull request merged**
