### PR TITLE
[REVIEW] Delete legacy files

### LINKED ISSUE #160: [BUG] Update hausdorff.hpp to libcudf++
* Eliminate use of gdf_column in shapefile APIs.
* Remove all raw RMM_ALLOC/RMM_FREE and replace with rmm::device_buffer / device_vector.
* Add appropriate CUSPATIAL_EXPECTS calls. See #153

### PR DESCRIPTION
**Pull request by cwharris**
Closes #160.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by cwharris** [comment]
@trxcllnt `get_ts_struct` is used in `traj_test_soa_locust.py`. Should I delete that as well?

**Comment by thomcom** [comment]
I vote we leave the demos in, but in an upcoming PR lightly refactor them to work without legacy code. Then we'll use them as potential templates for more notebooks.

**Comment by harrism** [comment]
Agree. Please file an issue for updating the demos.

**Comment by trxcllnt** [comment]
Yeah I'm translating the demos into notebooks. We don't need the legacy source files, I've already got cuDf reading the demo JSON data. If there's anything we need to cross-reference, we can look it up in the git history.

**Comment by cwharris** [comment]
Mission
-
Eliminate Legacy Code

Status:
-

**Comment by harrism** [comment]
Haha nice work. :)

**Pull request merged**
