### PR TITLE
Use ListColumn instead of build_list_column

### PR DESCRIPTION
**Pull request by mroeschke**
## Description
This API is planned for removal in cudf: https://github.com/rapidsai/cudf/pull/14786

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cuspatial/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Review by harrism — APPROVED** [review]
Thanks for getting out in front with this one!

**Review by isVoid — APPROVED** [review]
ty!

**Comment by harrism** [comment]
Pytests still failing due to `_from_columns`?

**Pull request merged**
